spring:
  elasticsearch:
    jest:
#      uris: http://10.40.132.140:9211  #大数据平台
      uris: http://10.40.132.121:9210   #天镜es5
      read-timeout: 30000
      connection-timeout: 30000
      multi-threaded: true

config:
  #大数据平台uyun推送告警地址
  alert-url: http://smart-view.nmic.cma1/store/openapi/v2/logs/push_batch?apikey=e10adc3949ba59abbe56e057f2gg88dd

  music-url: http://master.cma.cn/store/openapi/v2/datapoints/query?apikey=e10adc3949ba59abbe56e057f2gg88dd